export const FETCH_ALL_RECIPES = "FETCH_ALL_RECIPES";
export const FETCH_RECIPES_BY_SEARCH = "FETCH_RECIPES_BY_SEARCH";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";